apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/nikhil/k8s_project/mysql/backup"
