apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql
  labels:
    app: mysql
spec:
 type: NodePort
 selector:
   app: mysql
 ports:
   - port: 80
     targetPort: 3306
     nodePort: 30002

